### ISSUE TITLE
Can't install in versions below 1.50 of VS Code.

### ISSUE THREAD

**Issue by ericsouza** [loiane/java-spring-extension-pack#1]
Hey, @loiane. Where I work we can't get de latest version of VS Code. I Saw that this pack is set to work with ^1.50.0 version, but all extensions in this packs works fine with my version, 1.41.0. 

The Java Extensions Pack use this config:

"engines" : {
    "vscode": "^1.32.0"
}

Thanks :)

**Comment by loiane** [comment]
Hi @ericsouza please feel free to raise a PR to make this change, I'm ok with it, otherwise I can also apply it.

**Comment by loiane** [comment]
Fixed.
